version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/environments/cartpole"
    schedule:
      interval: "weekly"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
    groups:
      site:
        patterns:
          - "*"
