version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directories:
      - "/"
      - "/environments/ale/*"
      - "/environments/atcoder/*/*"
      - "/environments/codechef/*/*"
      - "/environments/gymnasium/*/*"
      - "/environments/gymnasium_robotics/*"
      - "/environments/highway_env/*"
      - "/environments/jackdaw/*"
      - "/environments/metaworld/*"
      - "/environments/minigrid/babyai"
      - "/environments/minigrid/minigrid/*"
      - "/environments/stable_retro/*"
      - "/environments/vizdoom/*"
    schedule:
      interval: "weekly"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
    groups:
      site:
        patterns:
          - "*"
