"""End-to-end test: drive the lib Server through a 5-submit run.

Validates the goal stated in docs/architecture.md Day 7:
"5 submits, each shows feedback, mean_return ~ -200 (good PD)".

Uses the reference PD policy from ``agents/pd_pendulum/policy.py`` —
the file lives outside ``src/hlbench/`` because it's a consumer, not
part of the server library (CLAUDE.md invariant 9). The test copies it
into the workspace's ``system/`` directory exactly the way a real agent
submission would.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

gym = pytest.importorskip("gymnasium")

from hlbench.core.server import Server  # noqa: E402

# Repo root (tests/ is one level under it).
_REPO_ROOT = Path(__file__).resolve().parents[1]
_REFERENCE_POLICY = _REPO_ROOT / "agents" / "pd_pendulum" / "policy.py"


@pytest.fixture
def workspace_with_reference_agent(tmp_path: Path):
    """Yield (server, workspace) where the reference PD agent is staged.

    runs_root is under tmp_path so each test gets its own isolated tree;
    workspace lives at runs_root/unknown/pendulum/<exp-id>/workspace/."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    ws = srv.workspace_dir
    # Real agent flow: agent writes/edits its code under workspace/system/.
    shutil.copy(_REFERENCE_POLICY, ws / "system" / "policy.py")
    return srv, ws


def test_workspace_has_required_three_things(tmp_path: Path) -> None:
    """Per CLAUDE.md invariant 5, workspace contains exactly:
    AGENTS.md, system/, feedback/. TASK.md is NOT staged — served via
    GET /task instead."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    ws = srv.workspace_dir
    assert (ws / "AGENTS.md").is_file()
    assert (ws / "system").is_dir()
    assert (ws / "feedback").is_dir()
    assert not (ws / "TASK.md").exists()
    # Top-level workspace entries exactly = {AGENTS.md, system, feedback}.
    entries = {p.name for p in ws.iterdir()}
    assert entries == {"AGENTS.md", "system", "feedback"}, entries


def test_canonical_run_layout(tmp_path: Path) -> None:
    """Per output.md §1: run_dir = runs_root/<model>/<env>/<exp-id>/
    with workspace/, checkpoints/, logs/ underneath."""
    srv = Server(
        env_id="pendulum",
        runs_root=tmp_path / "runs",
        model="claude-test",
        exp_id="alpha-1",
    )
    expected_run_dir = (tmp_path / "runs" / "claude-test" / "pendulum" / "alpha-1").resolve()
    assert srv.run_dir == expected_run_dir
    assert srv.workspace_dir == expected_run_dir / "workspace"
    assert srv.exp_id == "alpha-1"
    assert (expected_run_dir / "checkpoints").is_dir()
    assert (expected_run_dir / "logs").is_dir()


def test_autogenerated_exp_id_shape(tmp_path: Path) -> None:
    """Auto-generated exp_id is <timestamp>__<6-hex> per output.md §2.3."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    import re
    # <YYYY-MM-DDTHH-MM-SS>__<6-hex>
    assert re.fullmatch(
        r"\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}__[0-9a-f]{6}", srv.exp_id,
    ), f"unexpected exp_id shape: {srv.exp_id!r}"
    # Task text is served from the env-specific source via the lib method.
    task = srv.task_md_text()
    assert "Pendulum" in task, "env-specific TASK.md should be served, not placeholder"


def test_info_hides_baselines_and_seeds(tmp_path: Path) -> None:
    """Per CLAUDE.md invariant 2, /info NEVER reveals expert/random
    baselines or real seeds."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    info = srv.info()
    flat = json.dumps(info)
    assert "expert_baseline" not in flat
    assert "random_baseline" not in flat
    assert "real_seed" not in flat
    assert "heldout" not in flat
    # But the legitimate fields are present.
    assert info["env"] == "pendulum"
    assert info["env_meta"]["n_env_instances"] == 10000
    assert info["state"]["remaining_budget"] == 256
    assert info["state"]["is_finalized"] is False


def test_info_exposes_denied_imports_list(tmp_path: Path) -> None:
    """0.1.0a1: /info:denied_imports surfaces the AGENTS.md §3.2 list
    that the sandbox actually enforces, so agents don't need to parse
    the markdown to know what's blocked."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    info = srv.info()
    denied = info["denied_imports"]
    assert isinstance(denied, list) and len(denied) > 0
    # Sample-check that the high-impact entries are present and sorted.
    assert denied == sorted(denied)
    for must_contain in ("transformers", "requests", "stable_baselines3"):
        assert must_contain in denied, f"{must_contain} should be in denied list"


def test_info_state_advances_after_submits(workspace_with_reference_agent) -> None:
    """state.remaining_budget / n_submits update between submits."""
    srv, _ = workspace_with_reference_agent
    assert srv.info()["state"]["remaining_budget"] == 256
    srv.submit([0, 1])
    info = srv.info()
    assert info["state"]["remaining_budget"] == 254
    assert info["state"]["n_submits"] == 1
    assert info["state"]["n_successful_submits"] == 1
    assert info["state"]["last_submit_index"] == 0
    assert info["state"]["last_submit_status"] == "ok"


def test_five_submit_run_with_reference_pd_agent(
    workspace_with_reference_agent,
) -> None:
    """The Day 7 acceptance criterion: 5 submits of 4 episodes each on
    Pendulum-v1 with the reference PD agent. Each submit writes a
    well-formed feedback dir; the per-submit mean_return clears the
    "comfortably better than random" bar.

    Random baseline ~ -1200; expert ~ -150. We assert mean_return < -50
    (much better than random) and > -800 (a wide safety margin so this
    test isn't flaky on slow CI). The actual value is typically ~ -135."""
    srv, ws = workspace_with_reference_agent
    submit_means: list[float] = []

    # Submit env_instances 0..3, then 4..7, then 8..11, etc.
    for submit_i in range(5):
        env_instances = list(range(submit_i * 4, submit_i * 4 + 4))
        result = srv.submit(env_instances)
        assert result.status == "ok", \
            f"submit #{submit_i} failed: {result.status} {result.summary.get('errors')}"
        assert result.submit_id == submit_i

        summary = result.summary
        assert summary["n_episodes"] == 4
        assert summary["first_global_episode"] == submit_i * 4
        assert summary["env_instances"] == env_instances
        assert summary["timeouts"] == []
        assert summary["errors"] == []
        assert -800 < summary["mean_return"] < 0, \
            f"submit #{submit_i} mean_return {summary['mean_return']:.1f} outside expected band"
        submit_means.append(summary["mean_return"])

    # Final state: 5 successful submits, 20 episodes consumed.
    final = srv.info()["state"]
    assert final["remaining_budget"] == 256 - 20
    assert final["n_submits"] == 5
    assert final["n_successful_submits"] == 5
    assert final["last_submit_status"] == "ok"

    # Run-wide mean: PD reliably beats -400.
    overall_mean = sum(submit_means) / 5
    assert overall_mean < -50, "PD on Pendulum should be much better than 0"
    assert overall_mean > -400, \
        f"reference PD performing worse than expected (mean={overall_mean:.1f})"

    # Feedback layout: 5 submit dirs, each with summary.json + 4 episode
    # dirs containing trajectory.jsonl.
    fb_dir = ws / "feedback"
    submit_dirs = sorted(p.name for p in fb_dir.iterdir())
    assert submit_dirs == [f"submit_{i:03d}" for i in range(5)]
    for submit_i in range(5):
        sd = fb_dir / f"submit_{submit_i:03d}"
        assert (sd / "summary.json").is_file()
        assert not (sd / "errors.txt").exists()  # success → no submit-level error
        for ep_i in range(4):
            global_ep = submit_i * 4 + ep_i
            ep_dir = sd / "episodes" / f"ep_{global_ep:03d}"
            assert ep_dir.is_dir()
            traj = ep_dir / "trajectory.jsonl"
            lines = traj.read_text().strip().split("\n")
            assert len(lines) == 200, f"{traj} has {len(lines)} steps, want 200"


def test_finalize_runs_heldout_and_writes_run_json(
    workspace_with_reference_agent,
) -> None:
    """End-to-end Day 8 acceptance: submit a couple of times, finalize,
    then run.json contains a sane final_score, full held_out_returns
    array (256 floats), and the documented schema fields."""
    srv, ws = workspace_with_reference_agent

    srv.submit([0, 1, 2, 3])
    srv.submit([4, 5, 6, 7])

    result = srv.finalize()

    assert result.status == "completed"
    assert result.run_json_path.exists()
    assert result.held_out_returns is not None
    assert len(result.held_out_returns) == 256
    # PD on Pendulum: held-out mean is also in the -100 to -300 band.
    assert -800 < result.held_out_mean_return < 0
    # Normalized score: random=-1200, expert=-150; PD should clear ~80.
    assert 50 < result.final_score <= 120
    assert result.final_submit_index == 1
    assert result.error is None

    # File contents per output.md §3.1.
    doc = json.loads(result.run_json_path.read_text())
    assert doc["schema_version"] == "0.1"
    assert doc["env"] == "pendulum"
    assert doc["model"] == "unknown"  # default since we didn't pass one
    assert "exp_id" in doc
    assert doc["experiment_dimensions"]["episode_budget"] == 256
    assert doc["timing"]["wall_time_seconds"] > 0
    out = doc["outcome"]
    assert out["status"] == "completed"
    assert out["final_score"] == result.final_score
    assert out["final_submit_index"] == 1
    assert len(out["held_out_returns"]) == 256
    aux = out["auxiliary"]
    assert aux["n_submits"] == 2
    assert aux["n_successful_submits"] == 2
    assert aux["episodes_used"] == 8
    assert aux["mean_episodes_per_submit"] == 4.0
    assert aux["held_out_gap"] is not None
    # Day 11 metrics are populated for successful runs.
    assert aux["auc_in_loop"] is not None and 0 <= aux["auc_in_loop"] <= 120
    # PD on Pendulum reliably clears 80% normalized (~98 typical) → both
    # thresholds tripped at the first successful submit.
    assert aux["episodes_to_50pct"] == 4
    assert aux["episodes_to_80pct"] == 4
    assert doc["versions"]["harness"] == "0.1.0a1"
    assert doc["versions"]["env"] == "0.1"


def test_finalize_is_idempotent_and_blocks_further_submits(
    workspace_with_reference_agent,
) -> None:
    srv, _ = workspace_with_reference_agent
    srv.submit([0, 1])
    first = srv.finalize()
    second = srv.finalize()
    assert first is second  # same cached FinalResult

    with pytest.raises(RuntimeError, match="finalize"):
        srv.submit([2, 3])

    info = srv.info()
    assert info["state"]["is_finalized"] is True


def test_finalize_writes_error_when_no_policy_exists(tmp_path: Path) -> None:
    """A run that never had a working Policy still produces run.json,
    with status='error' rather than crashing in finalize().

    Pendulum now ships a starter policy that ``Server.__init__`` copies
    into ``workspace/system/policy.py`` — we delete it here to recreate
    the "no policy at all" scenario."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    # Wipe the auto-staged starter so heldout init has nothing to load.
    (srv.workspace_dir / "system" / "policy.py").unlink()
    result = srv.finalize()
    assert result.status == "error"
    assert result.final_score is None
    assert result.held_out_returns is None
    assert result.error is not None
    assert result.error["type"] == "HeldoutError"

    doc = json.loads(result.run_json_path.read_text())
    assert doc["outcome"]["status"] == "error"
    assert doc["outcome"]["error"]["type"] == "HeldoutError"


def test_starter_policy_auto_staged(tmp_path: Path) -> None:
    """``Server.__init__`` copies the env's starter policy into
    ``workspace/system/policy.py`` so the agent has a valid skeleton on
    turn 0. Pendulum's starter is the zero-torque baseline shipped at
    ``src/hlbench/envs/pendulum/starter_policy.py``."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    policy_path = srv.workspace_dir / "system" / "policy.py"
    assert policy_path.is_file()
    # Sanity check: the starter is a real Policy class, not a placeholder.
    src = policy_path.read_text()
    assert "class Policy" in src
    assert "def act" in src
    assert "def __init__" in src
    assert "def reset" in src


def test_starter_policy_not_overwritten_if_present(tmp_path: Path) -> None:
    """Re-instantiating Server on an existing run dir must NOT clobber
    a policy.py the agent already wrote."""
    runs_root = tmp_path / "runs"
    srv1 = Server(env_id="pendulum", runs_root=runs_root, exp_id="reuse")
    policy_path = srv1.workspace_dir / "system" / "policy.py"
    policy_path.write_text("# my own policy\nclass Policy: ...\n")

    # Re-init with the same exp_id ⇒ same workspace.
    srv2 = Server(env_id="pendulum", runs_root=runs_root, exp_id="reuse")
    assert srv2.workspace_dir == srv1.workspace_dir
    # Existing content is preserved; starter not re-staged.
    assert policy_path.read_text() == "# my own policy\nclass Policy: ...\n"


# ---------- checkpoints (output.md §5) ----------


def test_checkpoint_written_per_successful_submit(
    workspace_with_reference_agent,
) -> None:
    """Every successful submit copies its snapshot to
    run_dir/checkpoints/submit_NNN/ with _meta.json metadata."""
    srv, ws = workspace_with_reference_agent
    srv.submit([0, 1])
    srv.submit([2, 3, 4])

    cp_root = ws.parent / "checkpoints"
    assert cp_root.is_dir()
    assert sorted(p.name for p in cp_root.iterdir()) == ["submit_000", "submit_001"]

    # The policy file is preserved at the top level (flat layout per
    # output.md §5 — no nested system/).
    cp0 = cp_root / "submit_000"
    assert (cp0 / "policy.py").is_file()
    assert not (cp0 / "system").exists()
    # Content matches what we shipped to system/.
    assert (cp0 / "policy.py").read_text() == (ws / "system" / "policy.py").read_text()

    # _meta.json schema (output.md §5.2).
    meta = json.loads((cp0 / "_meta.json").read_text())
    assert meta["schema_version"] == "0.1"
    assert meta["submit_index"] == 0
    assert meta["validation_status"] == "ok"
    assert meta["validation_errors"] == []
    assert meta["n_episodes_requested"] == 2
    assert meta["remaining_budget_before"] == 256
    assert meta["remaining_budget_after"] == 254
    assert meta["snapshot_files"] == ["policy.py"]
    assert meta["snapshot_size_bytes"] > 0


def test_checkpoint_written_for_failed_submit(tmp_path: Path) -> None:
    """Failed submits also produce a checkpoint — output.md §5.3 says
    the snapshot is preserved so the agent can see what they submitted."""
    srv = Server(env_id="pendulum", runs_root=tmp_path / "runs")
    ws = srv.workspace_dir
    # Bad policy.py → init_error verdict, snapshot still preserved.
    (ws / "system" / "policy.py").write_text(
        "class Policy:\n"
        "    def __init__(self, **kw):\n"
        "        raise ValueError('boom')\n"
    )
    result = srv.submit([0, 1])
    assert result.status == "init_error"

    cp0 = ws.parent / "checkpoints" / "submit_000"
    assert (cp0 / "policy.py").is_file()
    meta = json.loads((cp0 / "_meta.json").read_text())
    assert meta["validation_status"] == "init_error"
    assert meta["validation_errors"] == [{"category": "init_error", "message": "init_error"}]
    assert meta["remaining_budget_after"] == 254  # full N consumed (Phase 5)


def test_run_json_artifacts_checkpoints_path(workspace_with_reference_agent) -> None:
    """run.json:artifacts.checkpoints is the relative path to the
    checkpoints directory (not None as in MVP)."""
    srv, ws = workspace_with_reference_agent
    srv.submit([0, 1])
    final = srv.finalize()
    doc = json.loads(final.run_json_path.read_text())
    assert doc["artifacts"]["checkpoints"] == "checkpoints"


def test_unknown_config_override_rejected(tmp_path: Path) -> None:
    """Misspelled override keys must fail loudly, not silently fall through."""
    with pytest.raises(ValueError, match="unknown config_overrides"):
        Server(
            env_id="pendulum",
            runs_root=tmp_path / "runs",
            config_overrides={"epiosde_budget": 8},  # typo
        )


def test_concurrent_submits_serialize_safely(workspace_with_reference_agent) -> None:
    """Two POST /submit threads launched simultaneously must NOT race on
    ``mkdir submit_NNN/`` — the second waits on Server's lock, then
    proceeds with the now-incremented ``state.n_submits``.

    Bug this guards against: ThreadingHTTPServer + retry-happy HTTP
    client. Without the lock, both threads read state.n_submits=0,
    both try mkdir submit_000/, second crashes with
    ``FileExistsError`` (Errno 17), HTTP returns 500."""
    import threading

    srv, _ = workspace_with_reference_agent
    results: list[Exception | int] = []
    barrier = threading.Barrier(2)  # release both threads at the same instant

    def _submit_burst(env_instances: list[int]) -> None:
        try:
            barrier.wait(timeout=5)  # both threads enter submit() back-to-back
            r = srv.submit(env_instances)
            results.append(r.submit_id)
        except Exception as e:
            results.append(e)

    t1 = threading.Thread(target=_submit_burst, args=([0, 1],))
    t2 = threading.Thread(target=_submit_burst, args=([2, 3],))
    t1.start()
    t2.start()
    t1.join(timeout=120)
    t2.join(timeout=120)
    assert not t1.is_alive() and not t2.is_alive(), "submit threads timed out"

    # Both must have completed without exception — the lock serialized
    # them rather than letting them race.
    assert all(isinstance(r, int) for r in results), f"got exceptions: {results}"
    assert sorted(results) == [0, 1], f"expected submit_ids 0 and 1, got {results}"

    # Both submit dirs exist on disk + each has a summary.json.
    fb = srv.workspace_dir / "feedback"
    assert (fb / "submit_000" / "summary.json").is_file()
    assert (fb / "submit_001" / "summary.json").is_file()

    # Server state advanced to 2 successful submits; remaining_budget
    # decremented by 4 episodes total.
    info = srv.info()
    assert info["state"]["n_submits"] == 2
    assert info["state"]["n_successful_submits"] == 2
    assert info["state"]["remaining_budget"] == 256 - 4
